services:
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    env_file:
      - ./backend/.env
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'