services:
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    volumes:
      - images_data:/app/public/images
    env_file:
      - ./backend/.env
    environment:
      DB_USER: sa
      DB_PASSWORD: "Password2025."
      DB_SERVER: host.docker.internal
      DB_DATABASE: ColorBlindTest
      DB_PORT: "1450"

    command: npm run dev
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
      
volumes:
  images_data: