USE [master]
GO
/****** Object:  Database [ColorBlindTest]    Script Date: 1.08.2025 16:02:40 ******/
CREATE DATABASE [ColorBlindTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ColorBlindTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ColorBlindTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'ColorBlindTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ColorBlindTest_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ColorBlindTest] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ColorBlindTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ColorBlindTest] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ColorBlindTest] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ColorBlindTest] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ColorBlindTest] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ColorBlindTest] SET ARITHABORT OFF 
GO
ALTER DATABASE [ColorBlindTest] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ColorBlindTest] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ColorBlindTest] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ColorBlindTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ColorBlindTest] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ColorBlindTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ColorBlindTest] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ColorBlindTest] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ColorBlindTest] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ColorBlindTest] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ColorBlindTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ColorBlindTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ColorBlindTest] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ColorBlindTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ColorBlindTest] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ColorBlindTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ColorBlindTest] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ColorBlindTest] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ColorBlindTest] SET  MULTI_USER 
GO
ALTER DATABASE [ColorBlindTest] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ColorBlindTest] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ColorBlindTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ColorBlindTest] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [ColorBlindTest] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ColorBlindTest] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ColorBlindTest] SET QUERY_STORE = ON
GO
ALTER DATABASE [ColorBlindTest] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ColorBlindTest]
GO
/****** Object:  Table [dbo].[Choices]    Script Date: 1.08.2025 16:02:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Choices](
	[question_id] [int] NOT NULL,
	[choice_text] [varchar](50) NOT NULL,
	[id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_Choices] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Questions]    Script Date: 1.08.2025 16:02:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Questions](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[question_text] [varchar](100) NOT NULL,
	[right_answer] [varchar](50) NOT NULL,
	[image_url] [varchar](500) NOT NULL,
 CONSTRAINT [PK_Questions] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tests]    Script Date: 1.08.2025 16:02:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tests](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[date] [datetime] NOT NULL,
	[time] [int] NULL,
	[num_correct_answers] [int] NOT NULL,
	[num_questions] [int] NOT NULL,
	[user_name] [varchar](50) NULL,
	[status] [varchar](50) NULL,
 CONSTRAINT [PK_Tests] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserAnswers]    Script Date: 1.08.2025 16:02:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserAnswers](
	[question_id] [int] NOT NULL,
	[test_id] [int] NOT NULL,
	[answer_text] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Choices]  WITH CHECK ADD  CONSTRAINT [FK_Choices_Questions] FOREIGN KEY([question_id])
REFERENCES [dbo].[Questions] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Choices] CHECK CONSTRAINT [FK_Choices_Questions]
GO
ALTER TABLE [dbo].[UserAnswers]  WITH CHECK ADD  CONSTRAINT [FK_UserAnswers_Questions] FOREIGN KEY([question_id])
REFERENCES [dbo].[Questions] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserAnswers] CHECK CONSTRAINT [FK_UserAnswers_Questions]
GO
ALTER TABLE [dbo].[UserAnswers]  WITH CHECK ADD  CONSTRAINT [FK_UserAnswers_Tests] FOREIGN KEY([test_id])
REFERENCES [dbo].[Tests] ([id])
GO
ALTER TABLE [dbo].[UserAnswers] CHECK CONSTRAINT [FK_UserAnswers_Tests]
GO
USE [master]
GO
ALTER DATABASE [ColorBlindTest] SET  READ_WRITE 
GO
